-- Seed: 38 Provinsi Indonesia (BPS 2024)
-- kode_bps follows BPS administrative coding standard.
-- Run this after 001_schema.sql.
-- Kabupaten/kota data: see README.md in this directory.

INSERT INTO wilayah (kode_bps, nama, level, parent_id) VALUES
  ('11', 'Aceh',                        'provinsi', NULL),
  ('12', 'Sumatera Utara',              'provinsi', NULL),
  ('13', 'Sumatera Barat',              'provinsi', NULL),
  ('14', 'Riau',                        'provinsi', NULL),
  ('15', 'Jambi',                       'provinsi', NULL),
  ('16', 'Sumatera Selatan',            'provinsi', NULL),
  ('17', 'Bengkulu',                    'provinsi', NULL),
  ('18', 'Lampung',                     'provinsi', NULL),
  ('19', 'Kepulauan Bangka Belitung',   'provinsi', NULL),
  ('21', 'Kepulauan Riau',              'provinsi', NULL),
  ('31', 'DKI Jakarta',                 'provinsi', NULL),
  ('32', 'Jawa Barat',                  'provinsi', NULL),
  ('33', 'Jawa Tengah',                 'provinsi', NULL),
  ('34', 'DI Yogyakarta',               'provinsi', NULL),
  ('35', 'Jawa Timur',                  'provinsi', NULL),
  ('36', 'Banten',                      'provinsi', NULL),
  ('51', 'Bali',                        'provinsi', NULL),
  ('52', 'Nusa Tenggara Barat',         'provinsi', NULL),
  ('53', 'Nusa Tenggara Timur',         'provinsi', NULL),
  ('61', 'Kalimantan Barat',            'provinsi', NULL),
  ('62', 'Kalimantan Tengah',           'provinsi', NULL),
  ('63', 'Kalimantan Selatan',          'provinsi', NULL),
  ('64', 'Kalimantan Timur',            'provinsi', NULL),
  ('65', 'Kalimantan Utara',            'provinsi', NULL),
  ('71', 'Sulawesi Utara',              'provinsi', NULL),
  ('72', 'Sulawesi Tengah',             'provinsi', NULL),
  ('73', 'Sulawesi Selatan',            'provinsi', NULL),
  ('74', 'Sulawesi Tenggara',           'provinsi', NULL),
  ('75', 'Gorontalo',                   'provinsi', NULL),
  ('76', 'Sulawesi Barat',              'provinsi', NULL),
  ('81', 'Maluku',                      'provinsi', NULL),
  ('82', 'Maluku Utara',                'provinsi', NULL),
  ('91', 'Papua Barat',                 'provinsi', NULL),
  ('92', 'Papua',                       'provinsi', NULL),
  ('93', 'Papua Selatan',               'provinsi', NULL),
  ('94', 'Papua Tengah',                'provinsi', NULL),
  ('95', 'Papua Pegunungan',            'provinsi', NULL),
  ('96', 'Papua Barat Daya',            'provinsi', NULL);
